import React, { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import ReportCard from './ReportCard';
import Header from './Header'; 

const ReportPage = () => {
  const [searchParams] = useSearchParams();
  const [reportData, setReportData] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    const dataParam = searchParams.get('data');
    if (dataParam) {
      try {
        const decodedJson = atob(dataParam);
        const parsedData = JSON.parse(decodedJson);
        setReportData(parsedData);
      } catch (e) {
        console.error("Failed to parse report data from URL", e);
        setError("The report link is invalid or corrupted.");
      }
    } else {
      setError("No report data found in the link.");
    }
  }, [searchParams]);

  return (
    <div className="min-h-screen bg-white font-sans text-gray-900 relative overflow-hidden">
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-32 -right-32 w-[700px] h-[700px] bg-black opacity-5 transform rotate-12"></div>
        <div className="absolute -bottom-40 -left-40 w-[800px] h-[800px] bg-black opacity-5 rounded-full"></div>
        <div className="absolute top-1/3 right-1/4 w-96 h-96 border-2 border-black opacity-5 rounded-full"></div>
      </div>

      <div className="relative z-10">
        <Header />
        <main className="container mx-auto p-4 md:p-8">
          <div className="max-w-4xl mx-auto">
            {/* Page Title */}
            <div className="text-center mb-12">
              <div className="inline-flex items-center gap-2 px-4 py-2 bg-gray-100 rounded-full mb-4">
                <div className="w-2 h-2 bg-black rounded-full animate-pulse"></div>
                <span className="text-xs tracking-wider uppercase font-medium text-gray-600">
                  Shared Report
                </span>
              </div>
              <h1 className="text-4xl md:text-5xl font-bold text-black mb-3">
                Safety Analysis Report
              </h1>
              <p className="text-gray-600">
                This report was generated by the Road Safety Expert System
              </p>
            </div>

            {error && (
              <div className="relative mb-8">
                <div className="absolute inset-0 bg-red-50 rounded-3xl transform rotate-1"></div>
                <div className="relative bg-white border-2 border-red-500 rounded-3xl p-8 shadow-xl">
                  <div className="flex items-start gap-4">
                    <div className="w-12 h-12 bg-red-500 rounded-xl flex items-center justify-center text-2xl text-white flex-shrink-0">
                      ⚠️
                    </div>
                    <div>
                      <h3 className="text-xl font-bold text-red-900 mb-2">Error Loading Report</h3>
                      <p className="text-red-700">{error}</p>
                    </div>
                  </div>
                </div>
              </div>
            )}
            
            {reportData && <ReportCard data={reportData} isSharedView={true} />}
          </div>
        </main>
      </div>
    </div>
  );
};

export default ReportPage;